/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package tugas_p5;

import java.awt.Image;
import java.text.DecimalFormat;
import javax.swing.JOptionPane;
import java.sql.Connection;
import java.sql.DriverManager;
import java.sql.PreparedStatement;
import java.sql.SQLException;
import javax.swing.ImageIcon;

public class Menu_Penjualan extends javax.swing.JFrame {

    /**
     * Creates new form Menu_Penjualan
     */
    
    private javax.swing.ButtonGroup groupTipe;
    
    public Menu_Penjualan() {
        initComponents();
        
        groupTipe = new javax.swing.ButtonGroup();
        groupTipe.add(tipe36);
        groupTipe.add(tipe45);
        groupTipe.add(tipe54);
        
        luasTanahAsli.setEditable(false);
        hargaBangunan.setEditable(false);
        hargaTanah.setEditable(false);
        luasTanahTersedia.setEditable(false);
        harga.setEditable(false);
        ppn.setEditable(false);
    }
    
    private void clearForm() {
        namaPemesan.setText("");
        hargaTanah.setText("");
        hargaBangunan.setText("");
        tipe36.setSelected(false);
        tipe45.setSelected(false);
        tipe54.setSelected(false);
        luasTanahAsli.setText("");
        luasTanahTersedia.setText("");
        harga.setText("");
        DP.setText("");
        lamaCicilan.setText("");
        ppn.setText("");
        totalCicilan.setText("");
        Setuju.setSelected(false);
        area.setSelectedIndex(0); // mengatur kembali ke item pertama
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        namaPemesan = new javax.swing.JTextField();
        hargaTanah = new javax.swing.JTextField();
        area = new javax.swing.JComboBox<>();
        jLabel4 = new javax.swing.JLabel();
        hargaBangunan = new javax.swing.JTextField();
        jLabel5 = new javax.swing.JLabel();
        tipe36 = new javax.swing.JRadioButton();
        tipe45 = new javax.swing.JRadioButton();
        tipe54 = new javax.swing.JRadioButton();
        jLabel6 = new javax.swing.JLabel();
        luasTanahAsli = new javax.swing.JTextField();
        jLabel7 = new javax.swing.JLabel();
        luasTanahTersedia = new javax.swing.JTextField();
        harga = new javax.swing.JTextField();
        DP = new javax.swing.JTextField();
        lamaCicilan = new javax.swing.JTextField();
        ppn = new javax.swing.JTextField();
        totalCicilan = new javax.swing.JTextField();
        jLabel8 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        jLabel11 = new javax.swing.JLabel();
        jLabel12 = new javax.swing.JLabel();
        jLabel13 = new javax.swing.JLabel();
        Setuju = new javax.swing.JCheckBox();
        proses = new javax.swing.JButton();
        simpan = new javax.swing.JButton();
        clear = new javax.swing.JButton();
        jLabel15 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Yafi Mahadika");

        jLabel1.setText("Nama Pemesan");

        jLabel2.setText("Harga Tanah/m2");

        jLabel3.setText("Area");

        namaPemesan.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                namaPemesanActionPerformed(evt);
            }
        });

        hargaTanah.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                hargaTanahActionPerformed(evt);
            }
        });

        area.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Bougenvile", "Melati", "Flamboyan" }));
        area.addItemListener(new java.awt.event.ItemListener() {
            public void itemStateChanged(java.awt.event.ItemEvent evt) {
                areaItemStateChanged(evt);
            }
        });
        area.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                areaActionPerformed(evt);
            }
        });

        jLabel4.setText("Harga Bangunan");

        hargaBangunan.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                hargaBangunanActionPerformed(evt);
            }
        });

        jLabel5.setText("Tipe Rumah");

        tipe36.setText("Tipe-36");
        tipe36.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                tipe36ActionPerformed(evt);
            }
        });

        tipe45.setText("Tipe-45");
        tipe45.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                tipe45ActionPerformed(evt);
            }
        });

        tipe54.setText("Tipe-54");
        tipe54.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                tipe54ActionPerformed(evt);
            }
        });

        jLabel6.setText("Luas Tanah Asli");

        luasTanahAsli.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                luasTanahAsliActionPerformed(evt);
            }
        });

        jLabel7.setText("Luas Tanah Tersedia");

        luasTanahTersedia.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                luasTanahTersediaActionPerformed(evt);
            }
        });

        harga.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                hargaActionPerformed(evt);
            }
        });

        DP.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                DPActionPerformed(evt);
            }
        });

        lamaCicilan.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                lamaCicilanActionPerformed(evt);
            }
        });

        ppn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ppnActionPerformed(evt);
            }
        });

        totalCicilan.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                totalCicilanActionPerformed(evt);
            }
        });

        jLabel8.setText("Harga");

        jLabel9.setText("DP");

        jLabel10.setText("Lama Cicilan");

        jLabel11.setText("PPN (10%)");

        jLabel12.setText("Cicilan/bln");

        jLabel13.setText("Bulan");

        Setuju.setText("Setuju");
        Setuju.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                SetujuActionPerformed(evt);
            }
        });

        proses.setText("PROSES");
        proses.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                prosesActionPerformed(evt);
            }
        });

        simpan.setText("SIMPAN");
        simpan.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                simpanActionPerformed(evt);
            }
        });

        clear.setText("CLEAR");
        clear.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                clearActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(317, 317, 317)
                        .addComponent(proses)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(simpan)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(clear))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(60, 60, 60)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(layout.createSequentialGroup()
                                        .addGap(254, 254, 254)
                                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addComponent(tipe45)
                                            .addComponent(tipe36, javax.swing.GroupLayout.PREFERRED_SIZE, 90, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addComponent(tipe54))
                                        .addGap(18, 18, 18))
                                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addComponent(jLabel8, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 95, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addComponent(jLabel10, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 95, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addComponent(jLabel9, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 95, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addComponent(jLabel11, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 95, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addComponent(jLabel12, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 95, javax.swing.GroupLayout.PREFERRED_SIZE))
                                        .addGap(10, 10, 10)))
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(luasTanahAsli, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(luasTanahTersedia, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(harga, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(DP, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addGroup(layout.createSequentialGroup()
                                        .addComponent(lamaCicilan, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(jLabel13, javax.swing.GroupLayout.PREFERRED_SIZE, 38, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addComponent(ppn, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addGroup(layout.createSequentialGroup()
                                        .addComponent(totalCicilan, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(Setuju))
                                    .addComponent(jLabel7, javax.swing.GroupLayout.PREFERRED_SIZE, 118, javax.swing.GroupLayout.PREFERRED_SIZE)))
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addComponent(jLabel15, javax.swing.GroupLayout.PREFERRED_SIZE, 207, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addGroup(layout.createSequentialGroup()
                                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                            .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 95, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 95, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 95, javax.swing.GroupLayout.PREFERRED_SIZE))
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addComponent(namaPemesan, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addComponent(hargaTanah, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addComponent(area, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE))))
                                .addGap(47, 47, 47)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(layout.createSequentialGroup()
                                        .addComponent(jLabel5, javax.swing.GroupLayout.PREFERRED_SIZE, 95, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                        .addComponent(jLabel6, javax.swing.GroupLayout.PREFERRED_SIZE, 95, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addGroup(layout.createSequentialGroup()
                                        .addComponent(jLabel4, javax.swing.GroupLayout.PREFERRED_SIZE, 95, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                        .addComponent(hargaBangunan, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)))))))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(44, 44, 44)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(namaPemesan, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel4, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(hargaBangunan, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(hargaTanah, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel5, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel6, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addGap(3, 3, 3)
                                .addComponent(tipe36)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(tipe45)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(tipe54))
                            .addGroup(layout.createSequentialGroup()
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(luasTanahAsli, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jLabel7, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(luasTanahTersedia, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addGap(28, 28, 28)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(harga, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel8, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(0, 0, 0)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(DP, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel9, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(0, 0, 0)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(lamaCicilan, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel10, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel13, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(0, 0, 0)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(ppn, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel11, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(0, 0, 0)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(totalCicilan, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel12, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(Setuju, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(26, 26, 26)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(proses)
                            .addComponent(simpan)
                            .addComponent(clear))
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addGroup(layout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(area, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addComponent(jLabel15, javax.swing.GroupLayout.PREFERRED_SIZE, 150, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(159, 159, 159))))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void namaPemesanActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_namaPemesanActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_namaPemesanActionPerformed

    private void hargaTanahActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_hargaTanahActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_hargaTanahActionPerformed

    private void hargaBangunanActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_hargaBangunanActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_hargaBangunanActionPerformed

    private void tipe36ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_tipe36ActionPerformed
        luasTanahAsli.setText("90");
        luasTanahTersedia.setText("90");
    }//GEN-LAST:event_tipe36ActionPerformed

    private void luasTanahAsliActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_luasTanahAsliActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_luasTanahAsliActionPerformed

    private void luasTanahTersediaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_luasTanahTersediaActionPerformed
        
    }//GEN-LAST:event_luasTanahTersediaActionPerformed

    private void hargaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_hargaActionPerformed
        try {
            // Ambil nilai dari luasTanahAsli, hargaTanah, dan hargaBangunan
            int luasTanahAsliValue = Integer.parseInt(luasTanahAsli.getText());  // Ambil luas tanah asli
            int hargaTanahPerM2Value = Integer.parseInt(hargaTanah.getText());  // Ambil harga tanah per m2
            int hargaBangunanValue = Integer.parseInt(hargaBangunan.getText());  // Ambil harga bangunan

            // Hitung harga total berdasarkan rumus: (Luas Tanah Asli * Harga Tanah/M2) + Harga Bangunan
            int totalHarga = (luasTanahAsliValue * hargaTanahPerM2Value) + hargaBangunanValue;

            // Tampilkan hasil perhitungan ke dalam harga (di dalam JTextField harga)
            harga.setText(String.valueOf(totalHarga));
        } catch (NumberFormatException e) {
            // Tampilkan pesan jika format data salah
            harga.setText("Input tidak valid");
            System.out.println("Error: " + e.getMessage());
        }
    }//GEN-LAST:event_hargaActionPerformed

    private void DPActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_DPActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_DPActionPerformed

    private void lamaCicilanActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_lamaCicilanActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_lamaCicilanActionPerformed

    private void ppnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ppnActionPerformed
        try {
            // Ambil nilai harga dari JTextField harga (hasil dari hargaActionPerformed)
            int hargaValue = Integer.parseInt(harga.getText());

            // Hitung PPN 10% dari harga
            double ppnValue = hargaValue * 0.1;  // 10% dari harga

            // Gunakan DecimalFormat untuk menampilkan angka tanpa pemisah ribuan
            DecimalFormat formatter = new DecimalFormat("#");
            ppn.setText(formatter.format(ppnValue));  // Format angka tanpa pemisah ribuan

        } catch (NumberFormatException e) {
            // Tampilkan pesan jika format data salah
            ppn.setText("Input tidak valid");
            System.out.println("Error: " + e.getMessage());
        }
    }//GEN-LAST:event_ppnActionPerformed

    private void totalCicilanActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_totalCicilanActionPerformed
        try {
            // Ambil nilai dari harga (sudah dihitung sebelumnya dengan PPN)
            int hargaValue = Integer.parseInt(harga.getText());  // Ambil harga
            int ppnValue = Integer.parseInt(ppn.getText());  // Ambil PPN yang sudah dihitung sebelumnya
            int dpValue = Integer.parseInt(DP.getText());  // Ambil nilai DP
            int lamaCicilanValue = Integer.parseInt(lamaCicilan.getText());  // Ambil jumlah cicilan (bulan)

            // Hitung total harga setelah PPN dan dikurangi DP
            int totalHarga = hargaValue + ppnValue - dpValue;

            // Hitung cicilan per bulan
            int cicilanPerBulan = totalHarga / lamaCicilanValue;

            // Tampilkan hasil cicilan per bulan ke dalam JTextField totalCicilan
            totalCicilan.setText(String.valueOf(cicilanPerBulan));
        } catch (NumberFormatException e) {
            // Tangani error jika input tidak valid
            totalCicilan.setText("Input tidak valid");
            System.out.println("Error: " + e.getMessage());
        }
    }//GEN-LAST:event_totalCicilanActionPerformed

    private void simpanActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_simpanActionPerformed
        if (
            namaPemesan.getText().isEmpty() ||
            hargaTanah.getText().isEmpty() ||
            hargaBangunan.getText().isEmpty() ||
            (!tipe36.isSelected() && !tipe45.isSelected() && !tipe54.isSelected()) ||
            luasTanahAsli.getText().isEmpty() ||
            luasTanahTersedia.getText().isEmpty() ||
            harga.getText().isEmpty() ||
            DP.getText().isEmpty() ||
            lamaCicilan.getText().isEmpty() ||
            ppn.getText().isEmpty() ||
            totalCicilan.getText().isEmpty() ||
            !Setuju.isSelected()
        ) {
            JOptionPane.showMessageDialog(this, "Gagal Simpan! Semua data harus diisi dan disetujui.", "Error", JOptionPane.ERROR_MESSAGE);
            return;
        }
        
        try {
            // 1. Ambil data dari inputan form
            String nama = namaPemesan.getText();
            String areaPilihan = area.getSelectedItem().toString();
            String tipe = ""; // Cek tipe rumah mana yang dipilih
            if (tipe36.isSelected()) tipe = "Tipe 36";
            else if (tipe45.isSelected()) tipe = "Tipe 45";
            else if (tipe54.isSelected()) tipe = "Tipe 54";

            int luasTanah = Integer.parseInt(luasTanahAsli.getText());
            int hargaTotal = Integer.parseInt(harga.getText());
            int lama = Integer.parseInt(lamaCicilan.getText());
            int cicilanPerBulan = Integer.parseInt(totalCicilan.getText());

            // 2. Koneksi ke database
            String url = "jdbc:mysql://localhost:3306/db_perumahan?allowPublicKeyRetrieval=true&useSSL=false";
            String user = "root";
            String pass = ""; // ganti dengan password MySQL kamu

            Connection conn = DriverManager.getConnection(url, user, pass);

            // 3. Buat dan jalankan query insert
            String sql = "INSERT INTO pemesanan (nama_pemesan, area, tipe_rumah, luas_tanah, harga, lama_cicilan, cicilan_per_bulan) VALUES (?, ?, ?, ?, ?, ?, ?)";
            PreparedStatement pst = conn.prepareStatement(sql);
            pst.setString(1, nama);
            pst.setString(2, areaPilihan);
            pst.setString(3, tipe);
            pst.setInt(4, luasTanah);
            pst.setInt(5, hargaTotal);
            pst.setInt(6, lama);
            pst.setInt(7, cicilanPerBulan);

            pst.executeUpdate();
            JOptionPane.showMessageDialog(this, "Data berhasil disimpan!");

            this.dispose(); // Menutup form Menu_Penjualan
            new Form_Utama().setVisible(true); // Membuka form Form_Utama
        
            pst.close();
            conn.close();
        } catch (Exception e) {
            JOptionPane.showMessageDialog(this, "Gagal menyimpan data: " + e.getMessage());
        }
    }//GEN-LAST:event_simpanActionPerformed

    private void clearActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_clearActionPerformed
        namaPemesan.setText("");
        hargaTanah.setText("");
        hargaBangunan.setText("");
        luasTanahAsli.setText("");
        luasTanahTersedia.setText("");
        harga.setText("");
        ppn.setText("");
        totalCicilan.setText("");
        DP.setText("");
        lamaCicilan.setText("");
    }//GEN-LAST:event_clearActionPerformed

    private void tipe45ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_tipe45ActionPerformed
        luasTanahAsli.setText("120");
        luasTanahTersedia.setText("120");
    }//GEN-LAST:event_tipe45ActionPerformed

    private void tipe54ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_tipe54ActionPerformed
        luasTanahAsli.setText("140");
        luasTanahTersedia.setText("140");
    }//GEN-LAST:event_tipe54ActionPerformed

    private void areaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_areaActionPerformed
        String pilihan = area.getSelectedItem().toString();
        
        switch(pilihan) {
            case "Bougenvile":
                hargaBangunan.setText("90000000");
                hargaTanah.setText("500000");
                break;
            case "Melati":
                hargaBangunan.setText("120000000");
                hargaTanah.setText("600000");
                break;
            case "Flamboyan":
                hargaBangunan.setText("150000000");
                hargaTanah.setText("700000");
                break;
            default:
                hargaBangunan.setText("");
                hargaTanah.setText("");
                break;
        }
    }//GEN-LAST:event_areaActionPerformed

    private void SetujuActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_SetujuActionPerformed
        if (Setuju.isSelected()) {
            JOptionPane.showMessageDialog(null, 
                "PELANGGAN KONFIRM/SETUJU", 
                "kotak konfirmasi", 
                JOptionPane.INFORMATION_MESSAGE);
        }
    }//GEN-LAST:event_SetujuActionPerformed

    private void prosesActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_prosesActionPerformed
        if (
            namaPemesan.getText().isEmpty() ||
            hargaTanah.getText().isEmpty() ||
            hargaBangunan.getText().isEmpty() ||
            (!tipe36.isSelected() && !tipe45.isSelected() && !tipe54.isSelected()) ||
            luasTanahAsli.getText().isEmpty() ||
            luasTanahTersedia.getText().isEmpty() ||
            harga.getText().isEmpty() ||
            DP.getText().isEmpty() ||
            lamaCicilan.getText().isEmpty() ||
            ppn.getText().isEmpty() ||
            totalCicilan.getText().isEmpty() ||
            !Setuju.isSelected()
        ) {
            JOptionPane.showMessageDialog(this, "Gagal Proses! Semua data harus diisi dan disetujui.", "Error", JOptionPane.ERROR_MESSAGE);
            return;
        }

        try {
            // 1. Ambil data dari inputan form
            String nama = namaPemesan.getText();
            String areaPilihan = area.getSelectedItem().toString();
            String tipe = ""; // Cek tipe rumah mana yang dipilih
            if (tipe36.isSelected()) tipe = "Tipe 36";
            else if (tipe45.isSelected()) tipe = "Tipe 45";
            else if (tipe54.isSelected()) tipe = "Tipe 54";

            int luasTanah = Integer.parseInt(luasTanahAsli.getText());
            int hargaTotal = Integer.parseInt(harga.getText());
            int lama = Integer.parseInt(lamaCicilan.getText());
            int cicilanPerBulan = Integer.parseInt(totalCicilan.getText());

            // 2. Koneksi ke database
            String url = "jdbc:mysql://localhost:3306/db_perumahan?allowPublicKeyRetrieval=true&useSSL=false";
            String user = "root";
            String pass = ""; // ganti dengan password MySQL kamu

            Connection conn = DriverManager.getConnection(url, user, pass);

            // 3. Buat dan jalankan query insert
            String sql = "INSERT INTO pemesanan (nama_pemesan, area, tipe_rumah, luas_tanah, harga, lama_cicilan, cicilan_per_bulan) VALUES (?, ?, ?, ?, ?, ?, ?)";
            PreparedStatement pst = conn.prepareStatement(sql);
            pst.setString(1, nama);
            pst.setString(2, areaPilihan);
            pst.setString(3, tipe);
            pst.setInt(4, luasTanah);
            pst.setInt(5, hargaTotal);
            pst.setInt(6, lama);
            pst.setInt(7, cicilanPerBulan);

            pst.executeUpdate();
            JOptionPane.showMessageDialog(this, "Data berhasil disimpan!");

            pst.close();
            conn.close();
            clearForm();
            
        } catch (Exception e) {
            JOptionPane.showMessageDialog(this, "Gagal menyimpan data: " + e.getMessage());
        }
    }//GEN-LAST:event_prosesActionPerformed

    private void areaItemStateChanged(java.awt.event.ItemEvent evt) {//GEN-FIRST:event_areaItemStateChanged
        String pilihan = area.getSelectedItem().toString();
        String path = "";

        switch(pilihan) {
            case "Bougenvile":
                path = "/tugas_p5/Foto1.jpg";
                break;
            case "Melati":
                path = "/tugas_p5/Foto2.jpg";
                break;
            case "Flamboyan":
                path = "/tugas_p5/Foto3.jpg";
                break;
        }

        // Load gambar ke jLabel15
        ImageIcon icon = new ImageIcon(getClass().getResource(path));
        if (icon != null) {
            Image image = icon.getImage().getScaledInstance(jLabel15.getWidth(), jLabel15.getHeight(), Image.SCALE_SMOOTH);
            jLabel15.setIcon(new ImageIcon(image));
        } else {
            System.out.println("Gambar tidak ditemukan: " + path);
        }
    }//GEN-LAST:event_areaItemStateChanged

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Menu_Penjualan.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Menu_Penjualan.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Menu_Penjualan.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Menu_Penjualan.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Menu_Penjualan().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextField DP;
    private javax.swing.JCheckBox Setuju;
    private javax.swing.JComboBox<String> area;
    private javax.swing.JButton clear;
    private javax.swing.JTextField harga;
    private javax.swing.JTextField hargaBangunan;
    private javax.swing.JTextField hargaTanah;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JTextField lamaCicilan;
    private javax.swing.JTextField luasTanahAsli;
    private javax.swing.JTextField luasTanahTersedia;
    private javax.swing.JTextField namaPemesan;
    private javax.swing.JTextField ppn;
    private javax.swing.JButton proses;
    private javax.swing.JButton simpan;
    private javax.swing.JRadioButton tipe36;
    private javax.swing.JRadioButton tipe45;
    private javax.swing.JRadioButton tipe54;
    private javax.swing.JTextField totalCicilan;
    // End of variables declaration//GEN-END:variables
}
